ref: 
  id: "GRCh38"
  url: "https://ftp-trace.ncbi.nlm.nih.gov/ReferenceSamples/giab/release/references/GRCh38/GRCh38_GIABv3_no_alt_analysis_set_maskedGRC_decoys_MAP2K3_KMT2C_KCNJ18.fasta.gz"
chain: 
  pat:
    url: "https://42basepairs.com/download/s3/human-pangenomics/T2T/HG002/assemblies/changes/GRCh38_to_hg002v1.1.pat.chain.gz"
    md5: "bc5bc5c548b2ded707eeba1143494d46"
  mat:
    url: "https://42basepairs.com/download/s3/human-pangenomics/T2T/HG002/assemblies/changes/GRCh38_to_hg002v1.1.mat.chain.gz"
    md5: "ea3b882a9c65137b6f1a844e34180a84"
adotto:
  url: https://zenodo.org/records/13987414/files/adotto_TRregions_v1.2.1.bed.gz
  md5: "3832640dcc26a420c34725136ec5b35d"
base:
  vcf: s3://giab-data/defrabb_runs/20250117_v0.020_HG002Q100v1.1/results/draft_benchmarksets/GRCh38_HG002-T2TQ100v1.1-dipz2k_stvar-excluded/GRCh38_HG2-T2TQ100-V1.1_stvar_dipcall-z2k.vcf.gz
  vcfidx: s3://giab-data/defrabb_runs/20250117_v0.020_HG002Q100v1.1/results/draft_benchmarksets/GRCh38_HG002-T2TQ100v1.1-dipz2k_stvar-excluded/GRCh38_HG2-T2TQ100-V1.1_stvar_dipcall-z2k.vcf.gz.tbi
  bed: s3://giab-data/defrabb_runs/20250117_v0.020_HG002Q100v1.1/results/draft_benchmarksets/GRCh38_HG002-T2TQ100v1.1-dipz2k_stvar-excluded/GRCh38_HG2-T2TQ100-V1.1_stvar_dipcall-z2k.benchmark.bed
callsets:
  comenius-svdss2:
    vcf: s3://giab-data/external_evaluations/20241113_v0.019_HG002Q100v1.1/evaluations/stvar/callsets/comenius-svdss2/svdss2.vcf.gz
    vcfidx: s3://giab-data/external_evaluations/20241113_v0.019_HG002Q100v1.1/evaluations/stvar/callsets/comenius-svdss2/svdss2.vcf.gz.tbi
    random_seed: 421
  illumina-dragen:
    vcf: s3://giab-data/external_evaluations/20241113_v0.019_HG002Q100v1.1/evaluations/stvar/callsets/illumina-dragen/DRAGEN_4.4.x_NIST_HG002.sv.vcf.gz
    vcfidx: s3://giab-data/external_evaluations/20241113_v0.019_HG002Q100v1.1/evaluations/stvar/callsets/illumina-dragen/DRAGEN_4.4.x_NIST_HG002.sv.vcf.gz.tbi
    random_seed: 214
  iter-dragen:
    vcf: s3://giab-data/external_evaluations/20241113_v0.019_HG002Q100v1.1/evaluations/stvar/callsets/iter-dragen/HG002.hg38.sv.vcf.gz
    vcfidx: s3://giab-data/external_evaluations/20241113_v0.019_HG002Q100v1.1/evaluations/stvar/callsets/iter-dragen/HG002.hg38.sv.vcf.gz.tbi
    random_seed: 124
  pacbio-sawfish:
    vcf: s3://giab-data/external_evaluations/20241113_v0.019_HG002Q100v1.1/evaluations/stvar/callsets/pacbio-sawfish/genotyped.sv.vcf.gz
    vcfidx: s3://giab-data/external_evaluations/20241113_v0.019_HG002Q100v1.1/evaluations/stvar/callsets/pacbio-sawfish/genotyped.sv.vcf.gz.tbi
    random_seed: 112
parameters:
  factors: ["INDEL","FPFN","TR"]  
  num_variants: 5